version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  download-and-filter:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Download Korea pbf
          command: wget https://download.geofabrik.de/asia/south-korea-latest.osm.pbf
      - run:
          name: Change permission
          command: chmod +x osmfilter32 osmconvert64
      - run:
          name: test
          command: ls -alRh .
      - run:
          name: test2
          command: uname -a
      - run:
          name: test3
          command: file ./osmfilter32
      - run:
          name: Filtering
          command: ./osmfilter32 south-korea-latest.osm --keep="water= highway=primary highway=motorway waterway= railway= natural=coastline narutal=peak aeroway=" > filtered.osm
      - run:
          name: Compress to pbf
          command: ./osmconvert64 filtered.osm -o=filtered.osm.pbf

workflows:
  south-korea:
    jobs:
      - download-and-filter
